### ISSUE TITLE
Task: Middleware for logging API calls

### ISSUE THREAD

**Issue by TariqueNasrullah** [SaifulJnU/crudApp#1]
- [x] Crete a Middleware which logs
	- [x] Client IP
	- [x] Response Http Status Code
	- [x] Latency
- [x] Use this middleware for every route

For logging you can use go's default log package. For more flexibility logrus/zap is good option.

**Comment by SaifulJnU** [comment]
Bhai, I have added the middleware. Please review my code and give me feedback.
![Screenshot from 2023-08-01 12-48-12](https://github.com/SaifulJnU/crudApp/assets/47039014/f2f55230-b45d-423f-9815-b38b04bd18ee)

**Comment by TariqueNasrullah** [comment]
A PR would be suitable for reviewing the code. The purpose of this task was to validate your understanding of Middleware. I guess your code serves the desired purpose.
